/**
 * @file	config_model_argument_descriptions.h
 * @brief	設定モデルノードで用いられる引数説明の宣言。
 * @author	Masakazu Asama <m-asama@ginzado.co.jp>
 */

#pragma once

#include "console_base.h"

extern msg cma_boolean_true_dscr[];
extern msg cma_boolean_false_dscr[];
extern msg cma_address_family_ipv4_dscr[];
extern msg cma_address_family_ipv6_dscr[];
extern msg cma_interfaces_interface_link_up_down_trap_enable_enumeration_disabled_dscr[];
extern msg cma_interfaces_interface_link_up_down_trap_enable_enumeration_enabled_dscr[];
extern msg cma_interfaces_state_interface_admin_status_enumeration_down_dscr[];
extern msg cma_interfaces_state_interface_admin_status_enumeration_testing_dscr[];
extern msg cma_interfaces_state_interface_admin_status_enumeration_up_dscr[];
extern msg cma_interfaces_state_interface_oper_status_enumeration_dormant_dscr[];
extern msg cma_interfaces_state_interface_oper_status_enumeration_down_dscr[];
extern msg cma_interfaces_state_interface_oper_status_enumeration_lower_layer_down_dscr[];
extern msg cma_interfaces_state_interface_oper_status_enumeration_not_present_dscr[];
extern msg cma_interfaces_state_interface_oper_status_enumeration_testing_dscr[];
extern msg cma_interfaces_state_interface_oper_status_enumeration_unknown_dscr[];
extern msg cma_interfaces_state_interface_oper_status_enumeration_up_dscr[];
extern msg cma_ip_address_origin_enumeration_dhcp_dscr[];
extern msg cma_ip_address_origin_enumeration_link_layer_dscr[];
extern msg cma_ip_address_origin_enumeration_other_dscr[];
extern msg cma_ip_address_origin_enumeration_random_dscr[];
extern msg cma_ip_address_origin_enumeration_static_dscr[];
extern msg cma_ipv6_address_status_enumeration_deprecated_dscr[];
extern msg cma_ipv6_address_status_enumeration_duplicate_dscr[];
extern msg cma_ipv6_address_status_enumeration_inaccessible_dscr[];
extern msg cma_ipv6_address_status_enumeration_invalid_dscr[];
extern msg cma_ipv6_address_status_enumeration_optimistic_dscr[];
extern msg cma_ipv6_address_status_enumeration_preferred_dscr[];
extern msg cma_ipv6_address_status_enumeration_tentative_dscr[];
extern msg cma_ipv6_address_status_enumeration_unknown_dscr[];
extern msg cma_ipv6_neighbor_state_enumeration_delay_dscr[];
extern msg cma_ipv6_neighbor_state_enumeration_incomplete_dscr[];
extern msg cma_ipv6_neighbor_state_enumeration_probe_dscr[];
extern msg cma_ipv6_neighbor_state_enumeration_reachable_dscr[];
extern msg cma_ipv6_neighbor_state_enumeration_stale_dscr[];
extern msg cma_neighbor_origin_enumeration_dynamic_dscr[];
extern msg cma_neighbor_origin_enumeration_other_dscr[];
extern msg cma_neighbor_origin_enumeration_static_dscr[];
extern msg cma_next_hop_classifiers_priority_enumeration_backup_dscr[];
extern msg cma_next_hop_classifiers_priority_enumeration_primary_dscr[];
extern msg cma_route_filter_allow_all_route_filter_dscr[];
extern msg cma_route_filter_deny_all_route_filter_dscr[];
extern msg cma_routing_instance_default_routing_instance_dscr[];
extern msg cma_routing_protocol_direct_dscr[];
extern msg cma_routing_protocol_static_dscr[];
extern msg cma_special_next_hop_special_next_hop_enumeration_blackhole_dscr[];
extern msg cma_special_next_hop_special_next_hop_enumeration_prohibit_dscr[];
extern msg cma_special_next_hop_special_next_hop_enumeration_receive_dscr[];
extern msg cma_special_next_hop_special_next_hop_enumeration_unreachable_dscr[];
